ARG VERSION=15
ARG PGVECTOR_VERSION=0.5.0
ARG IMAGE_TAG=$VERSION-bookworm

FROM postgres:$IMAGE_TAG
ARG VERSION
ARG PGVECTOR_VERSION

WORKDIR /lantern

RUN apt update \
    # Fix the locales package version to prevent unexpected updates
    && apt-mark hold locales \
    && apt install -y --no-install-recommends \
       build-essential \
       cmake \
       postgresql-server-dev-$VERSION \
       gdb \
       wget \
       python3-pip \
       python3-dev \
       sudo \
       curl \
       git-all \
       tmux \
       clang-format \
    && pip install libtmux --break-system-packages && \
    wget -O pgvector.tar.gz https://github.com/pgvector/pgvector/archive/refs/tags/v${PGVECTOR_VERSION}.tar.gz && \
    tar xzf pgvector.tar.gz && \
    cd pgvector-${PGVECTOR_VERSION} && \
    make && make install

COPY . .

# Build lantern
RUN rm -rf build \
    && mkdir build \
    && cd build \
    && cmake -DUSEARCH_NO_MARCH_NATIVE=ON -DCMAKE_BUILD_TYPE=Debug .. \
    && make install

# Install benchmarking tools in build folder
RUN git clone https://github.com/lanterndata/benchmark \
    && cd benchmark \
    && pip install -r core/requirements.txt --break-system-packages \
    && pip install -r external/requirements.txt --break-system-packages
ENV DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
ENV LANTERN_DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres