ARG VERSION=16
ARG PGVECTOR_VERSION=0.5.0

# If you want to build the base image for different versions
# Refer to the base image Dockerfile here https://github.com/var77/postgres-docker-debug
FROM varik77/postgres:$VERSION-debug
ARG PGVECTOR_VERSION

WORKDIR /lantern

USER root
ENV DEBIAN_FRONTEND=noninteractive
RUN pip install GitPython libtmux  && \
    wget -O pgvector.tar.gz https://github.com/pgvector/pgvector/archive/refs/tags/v${PGVECTOR_VERSION}.tar.gz && \
    tar xzf pgvector.tar.gz && \
    cd pgvector-${PGVECTOR_VERSION} && \
    make && make install

COPY . .

# Build lantern
RUN rm -rf build \
    && mkdir build \
    && cd build \
    && cmake -DUSEARCH_NO_MARCH_NATIVE=ON -DCMAKE_BUILD_TYPE=Debug .. \
    && make install

# Install benchmarking tools in build folder
RUN mkdir build/lantern \
    && git clone https://github.com/lanterndata/benchmark build/benchmark \
    && cd build/benchmark \
    && pip install -r core/requirements.txt \
    && pip install -r external/requirements.txt
ENV DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
ENV LANTERN_DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres

USER postgres
