ARG VERSION=15
ARG IMAGE_TAG=$VERSION-bookworm

FROM postgres:$IMAGE_TAG
ARG VERSION

WORKDIR /lanterndb

RUN apt update \
    # Fix the locales package version to prevent unexpected updates
    && apt-mark hold locales \
    && apt install -y --no-install-recommends \
       build-essential \
       cmake \
       postgresql-server-dev-$VERSION \
       postgresql-$VERSION-pgvector \
       gdb \
       wget \
       python3-pip \
       sudo \
       curl \
       git-all \
       tmux \
       clang-format \
    && pip install libtmux --break-system-packages

COPY . .

# Build lanterndb
RUN rm -rf build \
    && mkdir build \
    && cd build \
    && cmake -DUSEARCH_NO_MARCH_NATIVE=ON -DCMAKE_BUILD_TYPE=Debug .. \
    && make install