source 'https://rubygems.org'

gem 'sequel', '5.79'

gem "rspec", "~> 3.13"

gem "hashdiff", "~> 1.1"

gem "rainbow", "~> 3.1"

gem "pg", "~> 1.5"

gem 'pry', '~> 0.14.2'


gem "thor", "~> 1.3"

gem "pry-rescue", "~> 1.6"
