name: benchmark

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build
        id: build
        run: sudo su -c "PG_VERSION=15 USE_SOURCE=1 ./ci/scripts/build-linux.sh"
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

      - name: Run benchmarking
        id: test
        run: sudo su postgres -c "GITHUB_TOKEN=$GITHUB_TOKEN BASE_REF=$BASE_REF ./ci/scripts/run-benchmarks.sh"
        env:
          BASE_REF: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: |
            /tmp/benchmarks-out.json

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: ${{ github.event_name == 'pull_request' }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Benchmarks

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-path: /tmp/benchmarks-out.md
          edit-mode: replace
