name: benchmark
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
jobs:
  ubuntu-benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 15
            os: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Build
        id: build
        run: sudo su -c "PG_VERSION=$PG_VERSION USE_SOURCE=1  ./ci/scripts/build-linux.sh"
        env:
          PG_VERSION: ${{ matrix.postgres }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Run Benchmarks
        id: benchmark
        run: sudo su -c "PG_VERSION=$PG_VERSION GITHUB_OUTPUT=$GITHUB_OUTPUT ./ci/scripts/benchmark.sh"
        env:
          PG_VERSION: ${{ matrix.postgres }}
      - name: Upload Postgres logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: postgres-server-${{ matrix.postgres }}-logs
          path: |
            /tmp/pg-out.log
            /tmp/pg-error.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark.csv
          path: /tmp/benchmark.csv
