name: build
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      create_release:
        type: boolean
        description: "Create GitHub release for current version"
        required: false
        default: false
jobs:
  ubuntu-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 16
            os: ubuntu-22.04
          - postgres: 15
            os: ubuntu-22.04
          - postgres: 14
            os: ubuntu-22.04
          - postgres: 13
            os: ubuntu-22.04
          - postgres: 12
            os: ubuntu-22.04
          - postgres: 11
            os: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Build
        id: build
        run: sudo su -c "PG_VERSION=$PG_VERSION USE_SOURCE=1 GITHUB_OUTPUT=$GITHUB_OUTPUT BUILD_PACKAGES=1 ./ci/scripts/build-linux.sh"
        env:
          PG_VERSION: ${{ matrix.postgres }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      - name: Create Archive Package
        id: archive
        run: sudo su -c "GITHUB_OUTPUT=$GITHUB_OUTPUT ./ci/scripts/package-archive.sh"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.package_name }}
          path: ${{ steps.build.outputs.package_path }}
      - name: Upload archive package artifacts
        uses: actions/upload-artifact@v3
        if: ${{ steps.archive.outputs.archive_package_name != '' }}
        with:
          name: lantern-package
          path: ${{ steps.archive.outputs.archive_package_path }}
  ubuntu-package:
    runs-on: ubuntu-22.04
    needs: [ubuntu-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: lantern-package
          path: /tmp/lantern-package
      - name: Create universal package
        id: package
        run: sudo su -c "GITHUB_OUTPUT=$GITHUB_OUTPUT PACKAGE_EXTRAS=1 GITHUB_TOKEN=$GITHUB_TOKEN ./ci/scripts/universal-package.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package.outputs.package_name }}
          path: ${{ steps.package.outputs.package_path }}
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: lantern-package
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        id: create_release
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.create_release }}
        with:
          name: LanternDB v${{ steps.package.outputs.package_version }}
          tag_name: v${{ steps.package.outputs.package_version }}
          files: ${{ steps.package.outputs.package_path }}
          generate_release_notes: true
